language: go

go:
  - 1.7
  - 1.8
  - master
before_install:
  - sudo apt-get -qq update && sudo apt-get install -y flite-dev
  - go get github.com/golang/dep/...
install:
  - dep ensure
script:
  - for d in $(ls -d */ | grep -v vendor); do go test ./$d/...; done
